---
title: "Tema II: Descomposición de series"
subtitle: "Curso: Series Cronológicas"
author: 
  name: "Shu Wei Chou Chen"
  affiliation: "Posgrado en Estadística (UCR)<br> Posgrado en Matemática (UCR)"
format: 
  html:
    theme: 
      light: [sketchy, code_font_light.scss]
      dark: [sketchy, code_font_dark.scss]
lang: es
editor: visual
toc: true
toc-depth: 3
toc-location: left
toc-title: "Contenido"
toc-expand: 1
number-sections: true
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# librerías

```{r , message=FALSE , warning=FALSE}
library(ggplot2)
library(forecast)
library(fpp2)
```

# Descomposición aditiva

```{r}
contrayentes<-read.csv("contrayentes.csv",sep=";")
y<-ts(contrayentes$serie,start=c(1978,1),frequency=12)
aditivo<-decompose(y,type="additive")
names(aditivo)
aditivo$x #serie original
aditivo$seasonal #índices estacionales normalizados 
aditivo$trend #tendencia
aditivo$random #residuo
aditivo$figure #índices estacionales normalizados
```


```{r}
plot(aditivo)
autoplot(aditivo)
```

Las barras indican que cada gráfico debe ser considerado a su tamaño relativo. Se puede eliminarlo con ´range.bars=FALSE´.

```{r}
autoplot(aditivo, range.bars=FALSE)
```


```{r warning=FALSE}
tend <- aditivo$trend
tend.estac <- aditivo$trend+aditivo$seasonal
serie.aj.estac<-aditivo$x-aditivo$seasonal

autoplot(cbind(aditivo$x,tend,tend.estac,serie.aj.estac),col=1:4, size = 1)+
  xlab("tiempo")+ylab("contrayentes")+
  ggtitle("Serie contrayentes")+
  scale_color_manual(labels = c("serie original","tend", "tendencia+estac","serie.aj.estac"), 
                     values = 1:4)
```



# Descomposición multiplicativa

```{r}
turistas<-read.csv("turistas.csv",sep=";")
y<-ts(turistas$turistas,start=c(1991,1),frequency=12)
ts.plot(y)
multiplicativo<-decompose(y,type="multiplicative")
names(multiplicativo)
multiplicativo$x #serie original
multiplicativo$seasonal #índices estacionales normalizados 
multiplicativo$trend #tendencia
multiplicativo$random #residuo
multiplicativo$figure #índices estacionales normalizados
serie.aj.estac<-y/multiplicativo$seasonal
```


```{r}
plot(multiplicativo)
autoplot(multiplicativo,range.bars = TRUE)
```


```{r warning=FALSE}
tend <- multiplicativo$trend
tend.estac <- multiplicativo$trend * multiplicativo$seasonal
serie.aj.estac<-multiplicativo$x/multiplicativo$seasonal

autoplot(cbind(multiplicativo$x,tend,tend.estac,serie.aj.estac),col=1:4, size = 1)+
  xlab("tiempo")+ylab("contrayentes")+
  ggtitle("Serie contrayentes")+
  scale_color_manual(labels = c("serie original","tend", "tendencia+estac","serie.aj.estac"), 
                     values = 1:4)
```



# Descomposición STL

```{r}
y.stl1<-stl(y,t.window=20, s.window="periodic", robust=TRUE)
plot(y.stl1)
```


```{r}
y.stl2<-stl(y,t.window=5, s.window="periodic", robust=TRUE)
plot(y.stl2)
```


```{r}
y.stl3<-stl(y,t.window=5, s.window=3, robust=TRUE)
plot(y.stl3)
```



# Pronóstico con STL

```{r}
y
y.train<-window(y,start=c(1991,1),end=c(1999,12))
y.test<-window(y,start=c(2000,1),end=c(2000,12))
y.stl3<-stl(y.train,t.window=20, s.window="periodic", robust=TRUE)

#forecast.stl
class(y.stl3)
pronostico<-forecast(y.stl3,h=12)
#default: suavizamiento exponencial

names(pronostico)
plot(pronostico)
points(y.test,type="l",col=2)
```

```{r}
accuracy(pronostico)
accuracy(pronostico,y.test)
```

Verificación de los cálculos:

```{r}
#entrenamiento
e.train<-y.train-fitted(pronostico)
(MAE.train<-sum(abs(e.train))/length(e.train))
(RMSE<-sqrt(sum((e.train)^2)/length(e.train)))

#prueba
n<-12
e<- y.test - pronostico$mean
(MAE<-sum(abs(e))/n)
sqrt(MSE<-sum(e^2)/n)
MSE
(MAPE<-sum(abs(100*e/y.test))/n)
```

# Pronóstico con tendencia

```{r}
contrayentes<-read.csv("contrayentes.csv",sep=";")
y<-ts(contrayentes$serie,start=c(1978,1),frequency=12)
aditivo<-decompose(y,type="additive")
```


```{r}
plot(aditivo)
autoplot(aditivo)

tend <- aditivo$trend
tend.estac <- aditivo$trend+aditivo$seasonal
serie.aj.estac<-aditivo$x-aditivo$seasonal
```


```{r warning = TRUE}
autoplot(cbind(aditivo$x,tend,tend.estac,serie.aj.estac),col=1:4, size = 1.2)+
  xlab("tiempo")+ylab("contrayentes")+
  ggtitle("Serie contrayentes")+
  scale_color_manual(labels = c("serie original","tend", "tendencia+estac","serie.aj.estac"), 
                     values = 1:4)
```


# Regresión simple

```{r}
data<-data.frame(y,tend,tend.estac,serie.aj.estac,t=seq_along(y))
head(data)
tail(data)
mod<-lm(serie.aj.estac~t,data=data)
summary(mod)
```


```{r}
plot(as.numeric(data$y)~data$t,type="l")
abline(mod,col=2)
```


```{r}
tail(data)
pred<-predict(mod,newdata = data.frame(t=73:83))
accuracy(mod)        
```








